services:
  backend:
    build:
      context: ./backend
      target: prod
    environment:
      PORT: 3000
      LOG_LEVEL: info
      NODE_ENV: production
      MONGO_DB_CONNECTION: mongodb://produser:changeme@mongodb:27017/demo-prod?authSource=admin
    ports:
      - 3000:3000
      - 9999:9999

  mongodb:
    volumes:
      - db_data_prod:/data/db
      - db_init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: admin
      MONGO_DB: demo-prod
      MONGO_USER: produser
      MONGO_PASSWORD: changeme

volumes:
  db_data_prod:
    driver: local
    driver_opts:
      type: none
      device: $PWD/mongoDB/data/prod
      o: bind
  db_init:
    driver: local
    driver_opts:
      type: none
      device: $PWD/mongoDB/init.d
      o: bind
