services:
  backend:
    build:
      context: ./backend
      target: test
    environment:
      PORT: 3000
      LOG_LEVEL: debug
      NODE_ENV: production
      MONGO_DB_CONNECTION: mongodb://mongodb:27017/demo-integrationtest
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/test:/usr/src/app/test
      - ./backend/cucumber.js:/usr/src/app/cucumber.js

  mongodb:
    volumes:
      - db_data_test:/data/db
    environment:
      - MONGODB_DATABASE="demo-integrationtest"

  frontend:
    build:
      context: ./frontend
      target: test
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/test:/usr/src/app/test

volumes:
  db_data_test:
    driver: local
    driver_opts:
      type: none
      device: $PWD/mongoDB/data/test
      o: bind
